### ISSUE TITLE
Can history nodes work within a compound state?

### ISSUE THREAD

**Issue by tkuebler** [derkork/godot-statecharts#105]
I've discovered that for the state to be saved you have to exit the compound state - this is counter intuitive to me, although now that I know that I can design around it.   This is more of a question/suggestion than an issue.

My original state chart that does not save state on atomic task exit but is simpler and more intuitive IMO but does not work.
<img width="254" alt="image" src="https://github.com/derkork/godot-statecharts/assets/2801611/b2afc423-0663-4dae-932d-575288e6153b">

This works, but is more complex.
<img width="235" alt="image" src="https://github.com/derkork/godot-statecharts/assets/2801611/0d02a5b3-ceb4-4cdd-9704-985096056b0a">

I'm ok with the way it works now that I have figured it out, but it seems also keeping track of state inside a compound state would lead to simpler state charts in some cases.  You have to really read the documentation carefully to catch that you have to leave the state and return for the history to work.

**Comment by derkork** [comment]
The current implementation is according to the specification (https://statecharts.dev/glossary/history-state.html) and all state chart implementation that I have seen work this way. Interestingly, it is nowhere defined what should happen if you enter a history state without leaving the surrounding compound state, so technically this behaviour is _undefined_. I'm not quite sure what a useful behaviour would be in this case, especially if the compound state contains additional compound states.  E.g. let's assume we have this:

![image](https://github.com/derkork/godot-statecharts/assets/327257/80e5249c-8dab-4ea9-a978-e4fbe2b15f25)

We start in _B_ then go to _C_ then go to _A1_ which transitions to _A2_ which transitions to the _History State_. Where do we end up now? In _A1_ or in _C_ ? This probably depends on whether the history state is deep or not. But for the history state to be able to go back to A1 it would need to continuously track all sub-state changes (and their substate changes) which will lead into quite the rabbit hole. I guess that's the reason why the spec conveniently leaves this point out.
