### ISSUE TITLE
Having trouble with animation state trees

### ISSUE THREAD

**Issue by gaengberson** [derkork/godot-statecharts#106]
First off, this is a great tool. As a new dev it is helping me a great deal. 

The trouble I am running into is with nested animation trees. 

I can get this extension to manage animation state transitions easily when the animation tree root is classed as a state machine.

But if the animation tree root is a blend tree with state machines within it, I cannot effectively reference those animation tree state machines.

i.e., this works:
![image](https://github.com/derkork/godot-statecharts/assets/105949273/60e8550d-8bdd-4791-a432-13179e8071da)

but if I try to nest that same configuration within a blend tree (here marked torso), I cannot get it to work:
![image](https://github.com/derkork/godot-statecharts/assets/105949273/f49482e3-6665-4178-83f9-fe189217900e)

I tried naming the animation state chart node "torso/idle" etc., but /'s are not allowed. 
![image](https://github.com/derkork/godot-statecharts/assets/105949273/e7487089-82c0-4bf9-85fc-24f27d70d72c)

Edit: I just saw the error message. Without a workaround to this I can't figure out a pattern that wouldn't cause multiplicative states for separating leg and arm motions. Which means, despite the great functionality this offers, I can't use it.  
![image](https://github.com/derkork/godot-statecharts/assets/105949273/8e9190b3-0e8b-4d84-83a5-a8dd1fde89fa)

**Comment by derkork** [comment]
Sorry, i totally overlooked this one. So the AnimationTreeState is really just a small wrapper around the animation tree and I'm rather inclined to remove it from the package altogether as its really tool simplistic and it's easily the one I got the most tickets about. 

The animation tree state does nothing really fancy it just grabs the tree root at `_ready` and extracts the root state machine from it. Then when the state is entered it simply calls the travel function of the state machine with the state name. I think you're better off just making your own script that directly interfaces with your animation tree and calls the necessary methods. You can still call this custom script from the state chart nodes (using the the `state_entered` signal).

**Comment by gaengberson** [comment]
Thanks for the reply.

I would like to say that if should you decide to flesh this feature out and add support for nested animation trees it would help a lot.

One of the main things I am getting out of your addon is easily building in cooldown or lockout timers that can control things like iframes, recovery frames, and combo timers. Doing this natively is really difficult, and requires me to juggle courtines and timer nodes.

**Comment by derkork** [comment]
The thing is that there are a lot of ways to do animation control and any implementation I will choose will not work for someone. E.g. you can bury your animation tree state machine 3 levels deep in your animation tree. You could have more than one. You may decide to use a different animation tree per state. The _AnimationTreeState_ / _AnimationPlayerState_ nodes were some attempt at providing a "batteries included"-experience but I realize now that there are so many ways to do this, that either the tool falls flat (as the current implementation does) or its complexity will be the same as using the _AnimationTree_ / _AnimationPlayer_ directly in which nothing was gained. If you have an idea of a workable approach I'm all ears as right now, I don't have one.
