### ISSUE TITLE
Nodes hierarchy not detected

### ISSUE THREAD

**Issue by iekdosha** [derkork/godot-statecharts#107]
Hi :)

I am using Godot 4.21
The states hierarchy is not detected for me, I tried reloading the scene and it did not help.

I get these warnings:
![image](https://github.com/derkork/godot-statecharts/assets/35876294/d00d3b0a-7ba1-4025-94a6-05b70cece68c)

![image](https://github.com/derkork/godot-statecharts/assets/35876294/79fd60e0-8add-4db5-805d-c224cebe2d86)

---
Also, I cant seem to have the helper panel as showed in the tutorial:
![image](https://github.com/derkork/godot-statecharts/assets/35876294/97843833-f44e-4df0-ae00-7c692d112aa5)

**Comment by derkork** [comment]
Please make sure that you have enabled the plugin and also please restart the editor after installing the addon (just reloading the scene usually is not enough).

**Comment by iekdosha** [comment]
You are correct, restarting the editor did the job, thank you!

**Comment by derkork** [comment]
Awesome, glad it worked out! Have fun making your game!

**Comment by iekdosha** [comment]
@derkork thank you for making this awesome library!
Is there a community where I can ask questions about it, guides or more extensive documentation for it?

**Comment by derkork** [comment]
Well there is the [manual](https://github.com/derkork/godot-statecharts/blob/main/manual/manual.md), and I was hoping it  provides enough depth, so I would be very interested in improving this if you find it to be lacking information. Apart from that you can always ask questions here (just open up a ticket) and I also tend to hang around on the [Godot discord](https://discord.com/invite/zH7NUgz).
