### ISSUE TITLE
StateIsActiveGuard not working with delayed transitions

### ISSUE THREAD

**Issue by DrDonze** [derkork/godot-statecharts#109]
Hello,
First of all, thanks for this amazing project ! 
I've noticed a problem when I'm relying on a StateIsActiveGuard for a state transition when the state I'm listening to has a delayed transition.

For example, there is a state called WalkState and I have also other branches for managing animation with another state called WalkAnimation.
My animation transition to WalkAnimation rely on a StateIsActiveGuard listening to the activation of WalkState.
The problem is, if there is a delay to WalkState (delay_seconds property of the Transition), the WalkAnimation doesn't transit as if WalkState is not active (but it is active on the debug).
If I disable the delay, it is working as expected.

Am I the only one ? Am I doing something wrong ?

**Comment by derkork** [comment]
This sounds a bit like https://github.com/derkork/godot-statecharts/issues/103 to me. Guards do not trigger any transitions, they can only prevent transitions from happening. You need to have something that triggers the transition to _WalkAnimation_. If you can post your state chart I might be able to provide a suggestion on how to get the behavior you wan.

**Comment by DrDonze** [comment]
Thank you for your reply. Yes you're right it's exactly the same problem as #103, I thought transition with delay would still be processed as a "trigger" but I understand the limitations.
I'll find a better way to organize my tree. 
Thanks for the kind support !

**Comment by derkork** [comment]
Well, that being said this has come up enough times that I consider checking automatic transitions on every state change. I will need to find a way to make this less expensive and most of all predictable.

**Comment by derkork** [comment]
I opened https://github.com/derkork/godot-statecharts/issues/114 for this. I still need to think about the possible side effects but I think this would be really nice to have.
