### ISSUE TITLE
Icons are way too big

### ISSUE THREAD

**Issue by Shadowblitz16** [derkork/godot-statecharts#12]
Icons are way too big consider using the same size of icons that the rest of the editor uses

**Comment by derkork** [comment]
I am using a 4k display and for that the size is about right. Could you make a screenshot on how this looks on your machine?

**Comment by rubybrowncoat** [comment]
I don't know exactly what he means, but I do have this issue on my end.
![image](https://user-images.githubusercontent.com/973824/235845500-727e239e-5cdb-48d5-a180-1c8cefc2fd2e.png)

And to a lesser extent:
![image](https://user-images.githubusercontent.com/973824/235845634-65cb309e-8bb8-492e-a052-23eb034b9724.png)

**Comment by derkork** [comment]
@rubybrowncoat - this is a known editor bug and will be fixed in a future version of Godot (https://github.com/godotengine/godot/issues/57286)

**Comment by derkork** [comment]
I resized all icons to be 16x16 like the built-in icons, this seems to work better. I also found  a way for them to not be blurry at this size.
