### ISSUE TITLE
Can't make 2 column toolbar UI

### ISSUE THREAD

**Issue by eobet** [derkork/godot-statecharts#127]
The documentation shows the new UI as having two columns:

https://github.com/derkork/godot-statecharts/blob/main/manual/manual.md

But this is the most narrow I can drag it to:

![image](https://github.com/derkork/godot-statecharts/assets/3254196/2ebcb43d-1516-4809-ba6b-a39373fb59c9)

What information can I provide to help you debug this?

**Comment by derkork** [comment]
The screenshot was made in a very early version of the plugin where no minimum size was applied to the sidebar. This could lead to visual problems so a minimum size was introduced. However even with that in place I can resize the sidebar down to 3 horizontal icons. What resolution is your desktop at and what kind of scaling are you using? Also can you try to remove the minimum size of the editor sidebar panel and see if that improves the situation?

![image](https://github.com/derkork/godot-statecharts/assets/327257/044ababa-6b10-443e-9b62-0b46eb4da12e)

**Comment by eobet** [comment]
I'm normally using 175% display scaling (on Linux Wayland) although that currently has some core engine issues.

Right now, as a workaround, I'm at 100% but still seeing the same thing, can't resize down past 5 icons.

But thanks to your instructions, I now was able to set it to a low enough threshold so I got the 2 icon wide sidebar and so far it has both works and looks very nice!

**Comment by derkork** [comment]
This is great news, thanks for reporting back! I'll incorporate this change in the next release though I still really would like to understand why you are unable to get below 5 icons without the change.

**Comment by eobet** [comment]
> I still really would like to understand why you are unable to get below 5 icons without the change.

Perhaps it's because I'm running 175% desktop scaling in Gnome Wayland (and when I posted the above, I wasn't aware of the "prefer wayland" Editor Setting, which I unfortunately still can't use because it has some showstopper issues for me).
