### ISSUE TITLE
Consider using node diagram instead of scene tree for workflow

### ISSUE THREAD

**Issue by Shadowblitz16** [derkork/godot-statecharts#13]
instead of something like this...
![image](https://user-images.githubusercontent.com/2453707/235814564-4cd142b7-10c2-48a1-bd90-ad0c9af4c6db.png)

maybe something like this would be better?
![image](https://user-images.githubusercontent.com/2453707/235814586-1b612d27-9ae6-4f06-a349-b9e6e4db7551.png)
![image](https://user-images.githubusercontent.com/2453707/235814600-b8bb05c0-eb22-4657-a71d-a68737733032.png)

you might even be able to obsolete AnimationTree node.

**Comment by derkork** [comment]
The node diagram sure looks nice and would work for simple state machines but for any reasonably complex example it would quickly become very tedious to edit, as you need a way of expressing hierarchy in the diagram (these are state charts after all, not simple state machines). For example, the diagram for the frog in the platformer would look something like this:

![diagram](https://user-images.githubusercontent.com/327257/235840730-17079d34-3b80-41d3-bb18-7c3a8c763210.png)

Just clicking this together in a drawing program was a lot of mouse clicking and dragging and arranging stuff, whereas creating the same setup in nodes was done very quickly and easily, especially with the new sidebar, that @folt-a  made and that eliminates a lot of clicking. 

Editing is also a lot easier, e.g. you can just duplicate and drag nodes to a new parent node whereas with a diagram you would need to draw everything and editing hierarchies is very difficult (e.g. how would the editor distinguish between "i want to drag this node over here to make more space" and "i want to drag this node over here but it should move up to the parent state" ?). Also note how in the diagram the transitions back to _Grounded_ state are there multiple times, where in the tree I can just add one transition at the _Airborne_ node. 

There are also a few other reasons why I chose nodes over a diagram:

- they are already a familiar concept for users of Godot as almost everything is a node in Godot
- they are very easy to understand whereas the animation graph editor seems to confuse a lot of people - at least from my experience in the Godot Discord
- they allow you to use the built-in features for scene composition and inheritance to make your state charts - or parts of them - reusable
- the amount of code needed for graph editor would very likely exceed the amount of code needed for everything else. That time can better be spent elsewhere (e.g. good documentation) , especially given that a graph editor would not even be a better editing experience.

As for replacing the animation tree node, the intention of this library is to _complement_ existing functionality, not to replace it. This library is meant to provide easy state handling facilities for your game code, where animation trees do a similar thing for animations. They have _some_ overlap in that they use states but each one is specialized to do its particular thing well.  

So given all this, the library will not use diagrams for editing the state charts.
