### ISSUE TITLE
Make a release workflow

### ISSUE THREAD

**Issue by derkork** [derkork/godot-statecharts#14]
Right now the release is done manually, which is not too tedious but automating stuff is better. The release process should ideally:

- be triggered through a workflow on tagging a git commit with `vX.Y.Z`
- enter the new version into the plugin config file
- create a GitHub release
- submit the new version to the Godot Asset Library

**Comment by SirPigeonz** [comment]
@derkork You forgot to change plugin.cfg version to 0.7 ^^'

BTW Cool changes, love to see GSC to grow! :)

**Comment by derkork** [comment]
Thanks for the heads-up. I just released a fixed version.

**Comment by derkork** [comment]
I think adding an automated workflow is more effort than I want to spend since the actual releasing is really just a few clicks so I would need to make a ton of releases to even break-even on the effort spent. I added a [checklist ]( https://github.com/derkork/godot-statecharts/blob/main/RELEASE_CHECKLIST.md) to follow, so I don't forget anything. I think this is good enough for now so I'm going to close this.
