### ISSUE TITLE
Move the manual to Github Pages

### ISSUE THREAD

**Issue by joelgomes1994** [derkork/godot-statecharts#146]
Hello, @derkork! Are you interested into moving the manual to a dedicated site (`https://derkork.github.io/godot-statecharts`) using Github Pages?

I made [this](https://bgempire.github.io/bgforce) site some time ago to document a tool I made, and I could use the same template, change the theme, logos and separate topics into different .md files. The hosting is using Github Pages (so no domains and hosting costs are required), and editing it is pretty straightforward (as the [source documents](https://github.com/bgempire/bgforce/tree/gh-pages/_docs) are also Markdown). The source code is hosted in a [separate branch](https://github.com/bgempire/bgforce/tree/gh-pages), and deployed with Github Actions every time a change is pushed to the repository.

I could have made this and submitted a pull request already, but since I don't know if you're interested I thought it was better to ask first.

**Comment by derkork** [comment]
Hi @joelgomes1994! Well it sure looks nicer than the abomination we have right now - so it would definitely be an improvement  (we could even have consistent image sizes, yay!). I'm not sure about the separate branch, this sounds a bit like merge conflict hell, maybe we could just use a tag to mark the published version?

**Comment by joelgomes1994** [comment]
It's possible to deploy from a `docs` folder from the `main` branch:

![image](https://github.com/user-attachments/assets/653920a9-024a-40f4-86fa-b2ed607412ec)

The only problem is, when downloading the plugin from the Asset Library, it will also download the website source code as well (it's already doing that anyways). About the merge conflicts, the `gh-pages` branch is not even supposed to be merged from or to the `main` branch anyways, it would be totally dedicated to the docs, so I don't think it should be a concern.

But if you feel more comfortable, it's totally fine to use the `docs` folder in the `main` branch.

**Comment by derkork** [comment]
You can actually control what goes into the asset library zip, e.g. right now the manual is also part of the repo and is not inside the zip for the asset library (or if you download the zip manually from github). This is controlled through the [.gitattributes](https://github.com/derkork/godot-statecharts/blob/main/.gitattributes) file. So I'd prefer keeping this structure.

**Comment by joelgomes1994** [comment]
I'm working on this task in a fork, the temporary site was deployed to https://joelgomes1994.github.io/godot-statecharts. For now, I just copied and pasted the manual contents into different pages and fixed image paths.

The chages are in the https://github.com/joelgomes1994/godot-statecharts/tree/gh-pages branch, but in the docs folder, so this could be easily merged into the main branch once the pull request is created.

It's using the following configuration:
![image](https://github.com/user-attachments/assets/9b7f4fbd-68d5-436b-ba98-b66d007ec5e4)

I'll fix image sizing and other CSS issues.

**Comment by derkork** [comment]
This looks very nice! Thanks a lot for taking the time to do this!

**Comment by joelgomes1994** [comment]
Submitted the pull request #147

**Comment by derkork** [comment]
This is awesome thank you very much! I'll take this opportunity and slightly rework the manual so I will make some local changes on the branch before merging it. Again a huge thanks for doing this!

**Comment by derkork** [comment]
And merged! A big thanks again! I have taken the liberty to add your name to the footer, this would not have been possible without your work so I feel you deserve credit for this. Please let me know if this isn't ok with you, then I will remove it.

**Comment by joelgomes1994** [comment]
> And merged! A big thanks again! I have taken the liberty to add your name to the footer, this would not have been possible without your work so I feel you deserve credit for this. Please let me know if this isn't ok with you, then I will remove it.

That's great! I would prefer a link to my profile such as:
```html
Website created by <a target="_blank" href="https://github.com/joelgomes1994" style="color: #e18e39; text-decoration: none;">joelgomes1994</a>
```

![image](https://github.com/user-attachments/assets/eb6dd3ab-5858-4e09-a827-1739a6ffbf28)

Takes less space and is more useful. :smiley_cat: 

And thanks for merging the PR, nice work maintaining this project!

**Comment by derkork** [comment]
Done! Thanks again!
