### ISSUE TITLE
Godot 4.3: AssetLib image previews are broken

### ISSUE THREAD

**Issue by jonathan-durbin** [derkork/godot-statecharts#149]
Apologies if this is already known, but the asset library's preview images seem to be broken. This is on 4.3.

![image](https://github.com/user-attachments/assets/c59a0edd-8d4b-43c8-acb6-15c1e96e3d57)

**Comment by derkork** [comment]
Hi Jonathan, thank you very much for reporting this! I broke this when I reorganized the manual and forgot to update the links in the asset library. I have submitted new links to the asset library, once this gets approved the images should show again.
