### ISSUE TITLE
Strange lack of 'state transitions'

### ISSUE THREAD

**Issue by Dangomation** [derkork/godot-statecharts#20]
I don't even know whats going on here. Simply put I call '_state_chart.send_event("air")' and this happens:

- Doesn't transition?
- stays on the defaulted 'grounded' state
      _does _on_grounded_event_received(event) suppose to be receiving event 'air' nonstop?_
![image](https://github.com/derkork/godot-statecharts/assets/100386195/896c13d3-f4f4-4900-9f92-7ae14d5b7d8b)

Node tree:
![image](https://github.com/derkork/godot-statecharts/assets/100386195/4aedea66-ebf5-4b80-a4df-0f57541ec0e4)

I'm not crazy right? this is all you need to change states:
```gdscript
@onready var _state_chart = $StateChart as StateChart

func _on_grounded_state_physics_processing(delta):
	# temp gravity
	velocity.y += -2.5

	if self.is_on_floor() and jump_queued:
		velocity.y += 20
		_state_chart.send_event("air")

# This is just to show the complete picture:
func _on_grounded_state_input(event):
	pass

# Ariel Movement 🪂
func _on_air_state_entered():
	print("hello???")


func _on_air_state_physics_processing(delta):
	move_and_slide()

```
The signals are connected and just double check right now. Gonna start reinstalling everything including godot cause this is a silly problem tbh.

**Comment by Dangomation** [comment]
Nvm I'm just an idiot. Have a nice day

**Comment by derkork** [comment]
I'm glad you found a solution! If you have ideas/suggestions on how I could improve the [manual ](https://github.com/derkork/godot-statecharts/blob/main/manual/manual.md) so it is clearer how things work, please let me know. Good luck with your project!

**Comment by Dangomation** [comment]
I was trying to transition states though code like normal but I failed to identify the 'transition state' node was integral along with 'event' property and not just put the name of the node you wanted to 'send event' to as a StringName.
