### ISSUE TITLE
StateChartDebugger drops to 5 FPS

### ISSUE THREAD

**Issue by SirPigeonz** [derkork/godot-statecharts#24]
After upgrade to 0.4.0 my Player StateCharts is not working properly (bug in my code), so I tried to debug it but StateChartDebugger drops my project FPS to 5 from 60 :D

I'm sure it worked fine in 0.3.1.

**Comment by SirPigeonz** [comment]
I've checked demo platformer on fresh empty project, and it also lags because of StateChartDebugger.

**Comment by SirPigeonz** [comment]
I think I found the problem. It seems it updates the **whole** States History each frame, so with default 300 lines it starts to lag :D

Tmp fix to make it usable is to limit number of history entries to 20 for example.

**Comment by derkork** [comment]
I think I need to revisit how the history is held internally and rendered to the UI control. But something will come to mind.

**Comment by derkork** [comment]
Fixed in 0.4.1.

**Comment by SirPigeonz** [comment]
> Fixed in 0.4.1.

Nice! THX! I also like Settings tab rly nice addition! :)
