### ISSUE TITLE
How do I travel to a state when a animation ends?

### ISSUE THREAD

**Issue by Shadowblitz16** [derkork/godot-statecharts#25]
How do I use animation player states and transitions to travel to a state when the animation is over?

**Comment by Shadowblitz16** [comment]
thankyou

**Comment by Phanterm** [comment]
I would like to add to this, for those of you who do not use Animation Player states but would like similar functionality. 

![image](https://github.com/derkork/godot-statecharts/assets/3878045/cd4c27b2-ecee-4b96-b06c-75c5ad20deb0)

I've had good luck so far with adding a Call Method track on the last frame of an animation I want to transition to another state by invoking the `send_event` function with a `StringName` argument containing whatever value would cause the transition from the current state.

![image](https://github.com/derkork/godot-statecharts/assets/3878045/52988113-6f0a-402b-9c4e-e7ee8a5aab95)

Hope that's helpful to someone!
