### ISSUE TITLE
Add a way to trigger transitions via other node's signals

### ISSUE THREAD

**Issue by quimnuss** [derkork/godot-statecharts#32]
It be nice to be able to "trigger" transitions by connecting them to signals.

For example, connect NavigationAgent2D navigation_finished() to toIdle transition of the Run state.

At the moment we can workaround this by adding a function to a proxy that calls send_event with the appropiate event string.

What are your 5 cents on this?

**Comment by derkork** [comment]
For signals that have no arguments you can actually use the signal connection dialog's advanced mode. It allows you to add additional parameters to the function you want to call. E.g. in this example I add a StringName argument and send "navigation_is_done" as event:

![image](https://github.com/derkork/godot-statecharts/assets/327257/668f89b0-c6cb-478f-a23d-eb97d58bbf66)

Unfortunately this doesn't work for signals that have arguments, as you would need to strip the signal arguments and replace them with the name of the event you want to send. The dialog allows stripping of arguments (e.g. the unbind signal arguments section in the lower right). But right now you cannot combine both adding _and_ stripping of arguments in the dialog. I have opened a ticket for this a few weeks ago (https://github.com/godotengine/godot-proposals/issues/7542) but it may be a while until this comes (or I find the time to send them a PR implementing this). Apart from that you'll most likely need to stick to your proxy function solution, this is what I do as well.

**Comment by quimnuss** [comment]
Of course! I hadn't thought of adding the argument artificially. Awesome.
