### ISSUE TITLE
Is this a right way for using StateChart?

### ISSUE THREAD

**Issue by neilfranci** [derkork/godot-statecharts#38]
**Idk if this is the right way to use this many nodes but in the feature, there will be many other states with animation.**

![image](https://github.com/derkork/godot-statecharts/assets/66520542/24256d16-6367-4a71-83ec-14493234682c)

**Comment by derkork** [comment]
It looks ... excessive. You may want to consider using an AnimationTree + AnimationStateMachine to control your animations. There is built-in support for animation transitions, so you could make an animation follow another animation really easily without having to send a ton of events between the state chart and the animation player.  

Check: https://docs.godotengine.org/en/stable/tutorials/animation/animation_tree.html
