### ISSUE TITLE
Allow the sidebar to be moved to the right

### ISSUE THREAD

**Issue by Yagich** [derkork/godot-statecharts#47]
hey, really enjoying the plugin! i have a (hopefully 😅) quick usability suggestion. in my godot setup, the inspector is on the right side dock, so being able to have the State helper sidebar on the right closer to the inspector would be nice, since it seems to be intended that it's close to the inspector.

**Comment by derkork** [comment]
This makes a lot of sense, I'll add some way of moving this to the other side.
