### ISSUE TITLE
Add Beehave Style Integrated Debugger UI

### ISSUE THREAD

**Issue by meticoeus** [derkork/godot-statecharts#48]
The StateChartDebugger Node is useful for debugging a single statechart at a time but feels less than ideal when trying to debug startcharts for multiple scenes at once as it seems to require resizing each debug control node so they don't overlap for each debugger you want to see at once.

[BeeHave](https://github.com/bitbrain/beehave) has a very nice debug interface that is added as a tab in the Godot Debugger UI that lets you view each of the active behavior trees in the current scene. godot-statecharts could do something similar by taking the existing StateChartDebugger UI and auto registering each statechart into a Godot debugger interface tab with a list to pick which statechart to view the debug ui for. BeeHave adds an auto-loaded global script to handle the debug registration in the root behavior tree node.

Great library. I felt like I could finally get a handle on how to use statecharts/FSMs with the node based approach compared to relatively cumbersome (for non trivial charts) libraries like XState for javascript.

**Comment by derkork** [comment]
I'll check out how they do it in beehave, sounds like an interesting extension. I still like to have the abilitiy to inspect stuff in game though, so maybe the in-game debugger could also be enhanced to allow you to select one of the currently running state charts.

**Comment by meticoeus** [comment]
I also like the in game debugger for debugging the current statechart I'm working on. I think having both would be useful as the editor debugger would give you access to everything without having to make any changes to the scene trees while the in-game debugger is useful for focusing on debugging a particular statechart.

**Comment by derkork** [comment]
Ok we're getting somewhere:

![image](https://github.com/derkork/godot-statecharts/assets/327257/7b200b87-166c-492c-a417-bf1c71317d8f)

Still needs a lot of polishing, but it works in general.

**Comment by SirPigeonz** [comment]
Nice this will be very helpful for folks with 2 monitor settup!

It's also much more convinient to just select checkbox in the inspector, to add/remove your state chart monitored list and switch between debugging them in one place (like in Beehave) without modifing the scene tree :)

Thx fort this!

**Comment by derkork** [comment]
I have pushed a branch, in case you want to try it out.. https://github.com/derkork/godot-statecharts/tree/in-editor-debugger

**Comment by derkork** [comment]
Okay, so I've improved the implementation, we now also get the history in the editor and we have the same settings for ignoring parts of the history. 

![image](https://github.com/derkork/godot-statecharts/assets/327257/596b05a0-3e8f-46f9-8a00-51221f86a2fc)
![image](https://github.com/derkork/godot-statecharts/assets/327257/a78758a2-6f59-483c-8881-7a8f82859135)


The whole thing is opt-in now so the debugger only shows charts that have been marked for tracking in the editor.

![image](https://github.com/derkork/godot-statecharts/assets/327257/d2e55a7b-5861-4cbb-8902-18a93d0c78c5)

Once you reach a certain amount of state charts the amount of debug data gets really big, at which point the editor will be unhappy...

![image](https://github.com/derkork/godot-statecharts/assets/327257/51932383-b0f0-4e95-bcb0-01e051dd5a1b)

I'm not sure if this can be helped. I'm already culling messages whenever possible but when you have a thousand state charts in the game it will more or less try to send a thousand messages per frame when they are all busy doing something.

**Comment by derkork** [comment]
I have released the current state of implementation as 0.10.0 and submitted it to the asset library. It may not be perfect but I think its in a usable state now. Please give it a spin and let me know if there are issues. Thanks!
