### ISSUE TITLE
You can use expression guards as complex transition conditions

### ISSUE THREAD

**Issue by Glutoblop** [derkork/godot-statecharts#51]
If you never use the `event` field in transitions and always leave it blank, you can instead just use expression guards on your transitions and use these as conditional statements for the transitions.  
  
The only additional requirement for this work around is to emit a blank event [duration of your choosing] from a managing object and it works very cleanly to allow complex conditions to work in your transitions.  
  
Is there any reason you would be against having this as a fully built in supported feature instead of work arounds? 
Or if this was the intention then it works great!

**Comment by derkork** [comment]
What you describe is called a "Condition State" (https://statecharts.dev/glossary/condition-state.html). The idea is that you enter one state and then on entering you immediately switch to the next state based on some guards. And yes this is very much possible to do with the current implementation. 

Using an empty event is intended to signal transitions that should automatically run when the state is entered, so I'm not sure you want to use an empty event for this unless you want these transitions to run whenever the state is entered. But you can really use any other event name. E.g. you could use a generic event name like "tick" and then let everything react to this event.

![Untitled Diagram drawio](https://github.com/derkork/godot-statecharts/assets/327257/772677ab-da8c-4270-ab0b-9559e638afbf)

This way it would require no workarounds at all, just using the built-in functionality in a specific way.

**Comment by Glutoblop** [comment]
Using the `tick` event instead of blank is a good shout, it means I don't have to disable transition on enter to fix a recursive bug I was having with my work around.  Thanks!
