### ISSUE TITLE
"Could not find type "Transition" in current scope" error

### ISSUE THREAD

**Issue by Crusher48** [derkork/godot-statecharts#60]
My project is primarily a C# project, but is currently using Godot State Charts as an AI solution. However, this appears to create an issue where sometimes the project freezes on launch and produces a parser error: "Could not find type "Transition" in current scope", pointing to res://addons/godot_state_charts/state_chart.gd - line 13. Luckily, restarting the game always fixes this issue and manually building the project before launching the game usually prevents the issue from occurring, but it is still a significant workflow disruption.

Some solutions that have already been tried include deleting and reimporting the project, updating Godot versions (I am currently using the Godot 4.2 release), and clearing cache files that may point to a broken file link.

**Comment by derkork** [comment]
Hmm that is rather odd indeed. Did this also occur in previous Godot versions or only in 4.2?

**Comment by Crusher48** [comment]
I believe it occurred in every version I used it in, starting in either 4.1 or the 4.2 beta versions.

**Comment by derkork** [comment]
Okay, I just tried running it in 4.0 and 4.2 and that seemed to work. That's not helping you of course, but its kinda hard to fix a problem one cannot reproduce. Would you happen to have a demo project where this occurs that I could use to reproduce and fix the problem?

**Comment by derkork** [comment]
I'm closing this for now, as I cannot reproduce it and without being able to reproduce it I cannot really fix it. If you happen to have a sample project where this happens it would help tremendously.
