### ISSUE TITLE
State is not a child of state chart

### ISSUE THREAD

**Issue by vladthegreat** [derkork/godot-statecharts#66]
Following Godotneers tutorial I decided to apply some state chart to my player character for a simple animation transition. Before I could get very far, I get this notification. 

![image](https://github.com/derkork/godot-statecharts/assets/69280107/511ba000-b58a-4ff9-9ca7-1d09760a8cd2)

I cannot seem to find any previous issues like this, or google has no results. I have the latest Godot using Steam.

**Comment by derkork** [comment]
Are you getting any error messages in the console/debugger? Do the included examples work for you?

**Comment by vladthegreat** [comment]
You are amazing fast at responding! I decided to create a new project, it seems another asset i downloaded called OverheadCar2d 
had a few conflicting classes (I think State in particullar).
After starting a fresh project the StateChart does exactly as i expected! Thank you once again for the quick response.

**Comment by derkork** [comment]
Ah, so this seems related to #57. Thanks for letting me know!
