### ISSUE TITLE
StateIsActiveguard didn't work for me

### ISSUE THREAD

**Issue by hououkira** [derkork/godot-statecharts#67]
![image](https://github.com/derkork/godot-statecharts/assets/81728409/10d06d51-0f5b-47af-9e49-ff48655a6783)
So I wanted to change to BeingDraggedVFX when being dragged, so I monitored the BeingDragged state, but it wasn't working. And I changed to monitor MouseInside state just for debug:
![image](https://github.com/derkork/godot-statecharts/assets/81728409/a9802a0f-54eb-4674-b428-10420e8de361)
Then not beyond my expectation that didn't work at all, you can see it's still NotBeingDraggedVFX when MouseInside active
![image](https://github.com/derkork/godot-statecharts/assets/81728409/1e764279-8607-4bf2-87c6-f471fd1a8a68)
Then I tried to figrue out why and added a print in the addon script. So It actually just ran once in this scene. How could it monitor the change if it didn't run every frame? I don't know if this is a bug or I misunderstood it's effect.
![image](https://github.com/derkork/godot-statecharts/assets/81728409/76cd1414-67b3-417f-8254-cfb05b594305)
So I'd appreciate it if you told me what's going on here.

**Comment by derkork** [comment]
**Guards do not trigger transitions**, they are merely an additional condition that allows or forbids a transition to happen when it is being triggered. A transition is only triggered under the following conditions:

- all of:
  - the transition's owning state is currently active 
  - one of:
      - an event has just been sent to the state chart AND the transition's "event" property matches this event 
      - the state has just become active AND the transition has no "event" property set ([automatic transitions](https://statecharts.dev/glossary/automatic-transition.html))

**Comment by hououkira** [comment]
Thanks, I see that

**Comment by derkork** [comment]
#71 may help you once it is implemented.
