### ISSUE TITLE
Can't use "Change Type..." on state charts nodes 

### ISSUE THREAD

**Issue by eldyer** [derkork/godot-statecharts#68]
Hi! First of all, thanks for making this plugin - it's awesome!

I noticed that it's not possible to change the type of a state chart node (right click for example on an AtomicState -> select "Change Type..." -> select e.g. CompoundState, nothing happens). Is this a bug or a limitation?

**Comment by derkork** [comment]
Thank you very much for reporting this. This seems to be a bug/limitation of Godot. I have created an issue there: https://github.com/godotengine/godot/issues/86701 . I'm closing this, as it needs to be fixed in Godot and I have no control over this.
