### ISSUE TITLE
Typo in debugger history

### ISSUE THREAD

**Issue by eldyer** [derkork/godot-statecharts#70]
There is a little typo in the debugger history, should be "Exit" instead of "exiT".

https://github.com/derkork/godot-statecharts/blob/47b0a4aa5e0dcd5048d8b6639fe4ef973b66073e/addons/godot_state_charts/utilities/debugger_history.gd#L46C45-L46C45

**Comment by derkork** [comment]
This is actually on purpose to make the exit more visually distinct in the logs.

**Comment by eldyer** [comment]
Thanks, now I get it :grin:
