### ISSUE TITLE
Closure Function for Guard Expression

### ISSUE THREAD

**Issue by eilx** [derkork/godot-statecharts#73]
Would there be any issues using a closure for a guard expression? This *feels* odd to me and likely unnecessary to do, but perhaps I'm overthinking it.
```gdscript
# Set the Property
var value := true
state_chart.set_expression_property('closure_fn', func(): return value)

# Guard Expression
test_fn.call() == true
```
Apologies if this is the wrong place for this.

**Comment by derkork** [comment]
Using a closure is totally possible. Just make sure that the property name matches what you call in the guard expression. E.g.

```gdscript
state_chart.set_expression_property('test_fn', func(): return value)

# Guard Expression
test_fn.call()
```

If you just want to access a property of the current object you can also set the full object as an expression property, e.g.

```gdscript
var value = false

func _ready():
    state_chart.set_expression_property("me", self)
```

and then use  this expression in your guard:

```gdscript
me.value
```
