### ISSUE TITLE
Exported game showing state-chart script errors with AMD

### ISSUE THREAD

**Issue by bazsupport** [derkork/godot-statecharts#74]
- Godot version 4.2.1
- Users graphics card: AMD Radeon RX 6800 using the July 2023 drivers
- User is using Windows v10
- Game was exported using Performance+

When I exported the game and he tried it, the game would not start and gave this error:
![ApplicationFrameHost_qEIPr77CdC](https://github.com/derkork/godot-statecharts/assets/45674197/58c3935c-9dc3-42af-912d-0068452cd3a9)

After following the instructions, the game did start, but the following errors were showing:

`C:\Users\Rashid>mira.exe --rendering-driver opengl3

C:\Users\Rashid>Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org/
OpenGL API 3.3.0 Core Profile Context 23.Q3.230719 - Compatibility - Using Device: ATI Technologies Inc. - AMD Radeon RX 6800

SCRIPT ERROR: Parse Error: Could not find type "EditorDebuggerSession" in the current scope.
          at: GDScript::reload (res://addons/godot_state_charts/utilities/editor_debugger/editor_debugger_message.gd:91)
SCRIPT ERROR: Compile Error:
          at: GDScript::reload (res://addons/godot_state_charts/utilities/editor_debugger/editor_debugger_remote.gd:-1)
SCRIPT ERROR: Compile Error:
          at: GDScript::reload (res://addons/godot_state_charts/state_chart.gd:-1)
SCRIPT ERROR: Compile Error:
          at: GDScript::reload (res://player/scripts/player.gd:-1)
ERROR: Failed to load script "res://player/scripts/player.gd" with error "Compilation failed".
   at: load (modules/gdscript/gdscript.cpp:2788)`

Update:
This version of AMD graphics drivers seems to work and user was able to run the game:
23.12.1 - December 5th, 2023

**Comment by derkork** [comment]
The error messages regarding state charts should probably be fixed (even if they have no impact on being able to run the game). The game startup failure was very likely caused by the graphics card driver and not the addon.

**Comment by bazsupport** [comment]
Sounds good! Thanks again for this asset, super useful

**Comment by Devworks8** [comment]
I'm also receiving this compile error when running my exported game. I'm using version 0.12.0
