### ISSUE TITLE
Warning triangle on StateChartDebugger node (changed z-index)

### ISSUE THREAD

**Issue by perludum** [derkork/godot-statecharts#75]
The StateChartDebugger shows the warning triangle after changing its z-index.
The warning feels slightly too cautious here, because it’s always present in the node tree and a higher z-index for the debugger might be a common case.
Maybe a hint in the documentation about render order vs. input event order would suffice?

**Comment by derkork** [comment]
This warning built into godot, there is not a lot I can do about it.

**Comment by perludum** [comment]
Okay I see, thanks for your reply and many thanks for this awesome addon!
