### ISSUE TITLE
export _expression_properties to allow default values

### ISSUE THREAD

**Issue by megonemad1** [derkork/godot-statecharts#76]
the dictionary _expression_properties  contains known properties used in expression guards. having the dictionary exposed in the editor will allow for default values to be populated without bespoke code to do so.

**Comment by derkork** [comment]
I'm not really sure what the use case is for this one. You will need to set properties via code anyways, otherwise they would never change. And if they never change, why use them in the first place? Could you maybe go into a bit more detail which use case would profit from a feature like this?

**Comment by derkork** [comment]
I'm closing this as it is inactive.
