### ISSUE TITLE
Option to retry state transition on gate opening?

### ISSUE THREAD

**Issue by WeaselOnaStick** [derkork/godot-statecharts#78]
I want to propose a feature for state transitions described in the title.
 
Basically, we have a transition with both an event and a closed gate. I want there to be a toggle that makes the transition happen when a gate opens even after the event has been sent. That is without sending the event again, only sending it once before the gate opens.

I think the most optimal way would be is for a gate to somehow hook to relevant expression properties -> re-evaluate and send an internal transition event if gate is satisfied. 
Feel free to let me know if there's an easy way around with current tools (I tried transition delay but it only evaluates the gate at the start, not after delay) and if my proposed feature has any practical value

**Comment by WeaselOnaStick** [comment]
Yeah I was mainly asking because I had experience in programming where "gates" meant slightly different mechanism, and I was wondering if it would make sense to have that behavior here.

I ended up changing `Lookout(Atomic)` state into a compound chain of states (getting_up→rotate_to_outpost→go_to_outpost→lookout→rotate_to_rest_place→go_to_rest_place) and it didn't make sense to hardcode animation length values (since most animations were procedural), so I just used the gate I mentioned.

It's just that I didn't want to add these intermediate states, because it's not obvious if they should be inside Lookout or Resting.

**Comment by derkork** [comment]
Hmm okay, I think i have an idea now how this could work. Basically we have two parts in a transition:

1. the guard - this determines if the transition will be taken at all.
2. the delay - this determines when the transition actually will be executed after it has been taken

Now the delay currently can only be a timer, but if there was an option to use an expression as a delay, this could nicely solve the issue without introducing a lot of edge cases (except for the migration headache as this would be a breaking change... ).  So this would look like:


![image](https://github.com/derkork/godot-statecharts/assets/327257/1fe48f0d-69b8-415a-a4aa-09d47a53d71d)


And in code:

```
# called when the unit should travel somewhere
func travel_to(target):
     _state_chart.set_expression_property("target", target)
     _state_chart.send_event("travel")

func on_orienting_physics_processing(delta):
     # code here to orient the unit 
     ...
     if [unit is oriented]:
          _state_chart.send_event("oriented")

func on_moving_physics_processing(delta):
     # code here to move the unit where it needs to be
     ...
     if  [unit has arrived at target]:
         _state_chart.send_event("arrived")
```

What do you think?

**Comment by WeaselOnaStick** [comment]
Yeah, I think this makes much more sense than my initial approach. 
I think when I started I just looked at the platformer example where animation states and logic states are parallel/independent of each other and assumed that was the only right way to do it. Where as in my example animations _do_ in fact affect the logic.

**Comment by derkork** [comment]
With the new automatic transitions, you can actually do this without any custom delays. If you write a bit of code like this:

```gdscript
@onready var _animation_player:AnimationPlayer = %AnimationPlayer
@onready var _state_chart:StateChart = %StateChart

func _ready():
    animation_player.animation_changed.connect(_on_animation_changed)
 
func _on_animation_changed(_old_animation:StringName, new_animation:StringName):
   # set the name of the currently running animation as expression property.
   _state_chart.set_expression_property("animation", new_animation)
```

And then you can use automatic transitions from _Arriving at home_ , _Arriving at lookout_ and _Preparing for travel_  based on the current animation.
