### ISSUE TITLE
How to update this plugin properly?

### ISSUE THREAD

**Issue by bazsupport** [derkork/godot-statecharts#79]
Forgive the novice question, but I have tried many things and am unsuccessful to update this plugin.

I tried to reimport ignore the root folder because it was showing errors, however it didn't update to 0.13, it remained .11.1.
![Godot_4 2 1_VmxT4Pg0Y3](https://github.com/derkork/godot-statecharts/assets/45674197/087efe2e-bef8-415b-adc4-00a343c471f7)

I tried to delete the state_charts folder and reimport, but that threw many game breaking errors.

What is the proper way to update this plugin?

**Comment by bazsupport** [comment]
> Until the new asset store is released, I just delete it and place the new version with godot closed. Always update plugins with godot closed or the imports will break or some weird errors can occur.


Thank you very much! I now understand that I have to be out of the project and move the new version folder into the addons folder and replace everything from the Windows explorer. It worked very well!

**Comment by derkork** [comment]
I have added update instructions to the manual, thanks for reporting this! 

https://github.com/derkork/godot-statecharts/blob/main/manual/manual.md#updating-from-an-earlier-version
