### ISSUE TITLE
Wrong variable type declaration, which caused errors on clicking state nodes.

### ISSUE THREAD

**Issue by Zincles** [derkork/godot-statecharts#9]
## Problems
The newly added GUI editor is good, but there're still some issues on it.
When I click any state nodes, the editor push errors about 
"res://addons/godot_state_charts/utilities/editor_sidebar.gd:42 - Cannot call method 'get_children' on a null value"

![image](https://user-images.githubusercontent.com/91472426/233364710-93d81d8d-c1b3-4a92-b1a5-69c29268b11a.png)

## Solution
this problem is caused by wrong variable type declaration in `res://addons/godot_state_charts/utilities/editor_sidebar.gd` , line 14,
change:
```
@onready var _add_grid_container:GridContainer = %AddGridContainer
```
to
```
@onready var _add_grid_container:HFlowContainer = %AddGridContainer
```
would be fine.
![image](https://user-images.githubusercontent.com/91472426/233365339-50a40bbf-7ea6-4fee-89d6-c2a1d95516e9.png)

**Comment by derkork** [comment]
Thanks a lot for reporting this, I'll submit 0.2.1 to the asset library.
