### ISSUE TITLE
when duplicating an Atom with an ExpressionGuard the duplicated one points to the same ExpressionGuard

### ISSUE THREAD

**Issue by ebootdpr** [derkork/godot-statecharts#92]
When duplicating an atom with an already attached expressionguard, the new atom Shares the same reference to the expressionguard, so when you edit one, the other one also gets edited,
Im used to it now, but normal behavior should be that it creates a new expression guard.

**Comment by derkork** [comment]
There is unfortunately nothing I can do about it, this is just how the engine works. Whenever you duplicate a node any resourcce that the node is using is _not_ duplicated with it.  For example if you duplicate an area with a collision shape, the duplicated area will also refer to the same collision shape as the first one, so now both areas would share the same collision shape. Similarly now both transitions will share the same guard.
