### ISSUE TITLE
maintain/add stacktraces 

### ISSUE THREAD

**Issue by BasHamer** [derkork/godot-statecharts#95]
when there are a lot of nodes all using statecharts it can be difficult to figure out the origin of exceptions as your errors look like this.

![image](https://github.com/derkork/godot-statecharts/assets/139967/31941b49-f88c-48c6-b10d-dcbf040879e4)

**Comment by derkork** [comment]
These are errors that come from signal callbacks. So the library emits a signal which will then call attached signal handlers. These signal callbacks are handled by the engine and the stack traces they produce are beyond my control.
