### ISSUE TITLE
Parse error in 4.3.dev5 

### ISSUE THREAD

**Issue by BasilYes** [derkork/godot-statecharts#99]
This type of comments cause error after export project on upcoming godot 4.3.
![image](https://github.com/derkork/godot-statecharts/assets/36816595/dcfa5620-2a3b-4967-89e1-05710b0b16f2)

**Comment by derkork** [comment]
I can't seem to reproduce this locally. 
![image](https://github.com/derkork/godot-statecharts/assets/327257/770f0a0a-9511-42fd-a79d-9bd277a0d85f)

Are there any specific steps I need to take to make this happen?
